### ISSUE TITLE
Fix parsing of Object Store URLs in the API

### ISSUE THREAD

**Issue by victorges** [livepeer/studio#1205]
[This](https://github.com/livepeer/go-tools/pull/1/files#diff-6167f81f9154eef1998710aea373c85e57ab3fc3f6d68f28134a367daf999bb3L238
) change in the `go-tools` Object Store library caused a backward
incompatible update in the format of Object Store URLs. Previously, they 
allowed 1 or 2 path segments, the first one meaning the region and the 
second one the bucket, or just the bucket if no region is provided. The
new version does not allow a region to be provided and only allow a bucket
to be defined.

[The logic in the API to parse those URLs](https://github.com/livepeer/livepeer-com/blob/6b86fb011c94e9c6dee5c9837110e0bdf7f08663/packages/api/src/controllers/helpers.ts#L128) was implemented as simple as
possible, and so we only added support to the exact format we used for the
VOD Object Store.

In order to update `task-runner` with the latest version of `go-tools` lib, we
will need to fix the OS URLs in the database so they don't contain the region.
But to be able to change that in the DB, we also need to change the API logic 
first to support parsing only 1 path segment, as it now requires 2.

This should be a simple fix but I'm writing EOD on a rush before a PTO cause
I can't get started on this right now. Worst case this is just a reminder for myself
next week.

**Comment by victorges** [comment]
cc @cyberj0g what we were discussing on discord

**Comment by cyberj0g** [comment]
Good catch. The root issue seem to be not fully abstracting away object store operations and not having test coverage of these parts. The fix is probably to add some methods to `go-tools`, e.g. signature-related, so users don't need to have any knowledge of URL structure and specific OS implementation. When refactoring `go-tools`, I didn't know the URLs are parsed somewhere else in the code. @victorges could you help me figure out the list of updates to `go-tools` interface?
