### ISSUE TITLE
Mobile Example App

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1265]
This ticket likely needs further breakdown. 

https://github.com/livepeer/livepeer-demo-react-native

Currently, the existing example app currently doesn't work because it hits the old API. I think this a good point to reflect on the experience we want to deliver with this sample application and decide on the right approach. 

Requirements for a mobile sample application:

- Should allow users to quickly understand Studio's capabilities including broadcasting, playback, and On Demand. 
- Should allow users to quickly replicate the functionality in the application in their own app
- Should be compatible across devices (iOS / Android) 
- Should allow users to input a stream key to begin broadcasting
- Should allow users to seamlessly switch between front and back cameras
- Should allow users to use a default API key to upload and playback video. 
- Should use the Livepeer Player

Questions:
- Is the existing example app salvageable? Do we want to use this as an example app in the future? The app in the demo looks good from a design perspective but is missing On Demand?

**Comment by clacladev** [comment]
Here an update about the React Native app.
The app has not been really updated in 1.5 years. So it's broken in multiple ways. 

Here the issues:
- the API urls are pointing to the old endpoints, easy fix done on my branch
- the api authentication flow is broken, it needs to change (get `/api/user/me` if it's successful), easy fix
- the codebase does not build on Apple Silicon processors (M1, M2, etc). This is mainly due to the Camera and Video dependency being deprecated and not updated for latest macs (react-native-nodemediaclient). It needs to be replaced. I am in the process of doing this 
- React Native is way too old to actually make a migration. Everything breaks. So I created  a new React Native project and transferred all the still broken code from the old app and I am fixing it

What I am suggesting is that I take an extra day to fix all these issues (just replacing the camera is actually outstanding), then we can publish and updated React Native app that works and that is usable in hackatons and such. 

Later, depending on priorities, we can decide to dedicate some time and improve the codebase quality (modernise it a bit, medium effort) and add new features.
