### ISSUE TITLE
Livestream stops suddenly

### ISSUE THREAD

**Issue by Shih-Yu** [livepeer/studio#1313]
**Describe the bug (required)** A clear and concise description of what the bug
is.

- Livestream stops in the middle of a stream.

**Expected behavior (required)** A clear and concise description of what you
expected to happen.

- During a live stream, the feed just drops.

**To Reproduce (required)** Steps to reproduce the behavior:

1. Livestream from OBS
2. View in Studio dashboard
3. Wait for about 1-2 minutes to see stream drop in the dashboard.

**Device (required):**

- Device:  MacBook Pro
- OS: Monteery 12.6
- Browser: Brave
- Version: Version 1.43.93 Chromium: 105.0.5195.127 (Official Build) (arm64)

**Screenshots (optional)** If applicable, add screenshots to help explain your
problem.

https://user-images.githubusercontent.com/53620329/193059103-ea7c5906-7f22-4f6c-b1b5-e230b1641107.mov

**Comment by yondonfu** [comment]
I am able to reproduce this *if* recording is enabled for a stream (as is shown in the attached clip in the OP) by streaming using the following command:

```
ffmpeg -re -f lavfi -i testsrc=size=480x320:rate=30 -f lavfi -i sine -vf drawtext="text='%{localtime\:%X}':fontsize=20:fontcolor=white:x=7:y=7" -pix_fmt yuv420p -vcodec libx264 -vb 2000k -preset ultrafast -acodec aac -g 30 -f flv rtmp://rtmp.livepeer.com/live/<STREAM_KEY>
```

I am unable to reproduce this issue when recording is disabled for the stream.

Given that this issue seems to only occur when recording is enabled, I suspect that the recording bug that is causing https://github.com/livepeer/studio/issues/1314 and https://github.com/livepeer/studio/issues/1315 may be the root cause here. So, if that recording bug is fixed, this issue might be resolved as well.

**Comment by gioelecerati** [comment]
Without the recording enable the stream goes on, but the dashboard is unable to display the feed. 

I investigated a bit, and it looks like the field `isActive` in the stream is `false` after 1.30 minutes, even if ffmpeg is still running and the playback is working. On Grafana, in the log of the studio API, I don't see any call incoming to `/setactive` that may change this field.
I am also unable to find a point where the field is set to `false` by an UPDATE query

**Comment by Shih-Yu** [comment]
Closing:
https://discord.com/channels/423160867534929930/1025115716044718242/1025505105283403797
