### ISSUE TITLE
Decide between WebRTC and SRT (and RTMP)

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/studio#1407]

**Comment by pglowacky** [comment]
I've made the decision to pursue SRT as the mobile broadcasting protocol vs WebRTC for our mobile work this quarter. Here's my rationale:

- SRT is done, but there are bugs. Eli is already thinking about SRT, and it's on his list to start debugging. 
- We need to put SRT back into production no matter what because it's something that we've supported previously. 
- WebRTC although a well established protocol that Mist is very familiar with, has some technical unknowns which increases the risk of the overall project if we decided to pursue it as the broadcasting method.
