### ISSUE TITLE
Optimization of asset list on dashboard 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#1559]
On the VOD asset page we currently run 2 queries during page load: 
1- grab the first 20 assets
2- count how many assets there are total

Both of these block rendering of the asset list.

At high numbers of assets, this second query causes a noticeable delay in page render. The purpose of the second query is to render the number of total assets -- this does not need to block page load, and can appear after the page has loaded.

**Comment by victorges** [comment]
OK, investigating the code, I don't think there would be any API changes necessary here.

The step by step for the changes is:
 - Make [this asset-fetching logic](https://github.com/livepeer/livepeer-com/blob/51da460a9bf4d57cc73a8df3a5adfaa2870316a1/packages/www/components/Dashboard/AssetsTable/helpers.tsx#L86) **not** request for `count` on the `getAssets` request
 - Make [this `Table` component](https://github.com/livepeer/livepeer-com/blob/8ff6f905cc0d7265eed3a97201141ab057542c03/packages/www/components/Dashboard/Table/index.tsx#L587) (optionally) receive a separate fetcher for the `count` field. It could either be a specific `fetchCount` or maybe the `fetcher` prop could (optionally) be a list of fetchers instead of a single one. Then the results can be merged with `{...data1, ...data2}`
 - Update [the `DataTableComponent`](https://github.com/livepeer/livepeer-com/blob/8ff6f905cc0d7265eed3a97201141ab057542c03/packages/www/components/Dashboard/Table/index.tsx#L480) to allow the `data?.count` to not be present while loading, displaying some placeholder for that
 - Update [`AssetsTable` component](https://github.com/livepeer/livepeer-com/blob/50a97210991d404275a9b00e3bc1c180140ff00b/packages/www/components/Dashboard/AssetsTable/index.tsx#L77) to send a separate "count fetcher" to the `Table` component, however that is specified. This new fetcher should use the same `getAsset` function, with the only difference that it sets `count: true` as the current one and it can limit to 1 element in the response as we'll not really use that (I think it can't be `0` tho).

WDYT @clacladev, does this make sense? Since it is a front-end only change, do you think it's something you could pick up? I don't actually remember why this was assigned to me, but this is not more priority than the VOD token-gating stuff anyway so I'll only be able to postpone it. Not sure how urgent this is in general for it to be worth picking it up either, so I'll leave it up to you until we get any more signal for this.

**Comment by clacladev** [comment]
@victorges This was roughly my plan on how to do the change too, based on our December conversations.
I just don't think it will be a quick change, medium effort. But definitely feasible.
Depending on the other priorities I can pick it up now or later. But this is up to you @pglowacky

**Comment by victorges** [comment]
Yeah agreed that it doesn't look like a small change, which is why I wasn't able to do a quick fix myself. Thought it would be more straightforward for you, but maybe it's actually a considerable change. What would you say is the day/point estimate to complete this? We can update the ticket and keep it in backlog until we wanna prioritize it.
