### ISSUE TITLE
Add API endpoint that returns usage over time

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/studio#220]
The endpoint should accept a date range and return the total minutes transcoded per day over that range.

**Comment by yondonfu** [comment]
Since running a SQL query each time will be expensive, the current plan is to store daily global usage in a separate table (i.e. by running a daily cronjob to store a result based on a SQL query) and then the endpoint can return data from this table.

**Comment by yondonfu** [comment]
The schema for the global usage table could include the same fields used by the per-user usage endpoint:

- `date` (the date that the usage data corresponds to)
- `createdAt` (the timestamp at which the usage data was updated)
- `sourceSegmentsDuration`
- `transcodedSegmentsDuration`
- `sourceSegments`
- `transcodedSegments`

The API could expose:
- An endpoint (`/api/usage/update`?) that will run the SQL query for generating global usage data for the past day and update the DB. Might be helpful for this endpoint to accept a date so the endpoint can be used to store usage data for any specific date.
- An endpoint (`/api/usage`?) that accepts a date range and returns the usage data per day over that range

We may be able to use a [Vercel cronjob](https://vercel.com/docs/solutions/cron-jobs) to automate calls to the first endpoint once per day as that seems easier than creating a k8s cronjob.

Since the cronjob would only start storing usage data going forward, we may want to run a script to call the first endpoint to populate usage data in the table with past days as well.

TODOs based on the above:

- [ ] Implement new table and endpoints in livepeer-com
- [ ] Use auth middleware with admin API token for the first endpoint (storing usage data for a specific date)
- [ ] Create a cronjob
- [ ] Run script to populate table with usage data with past days
