### ISSUE TITLE
Technical plan for webhooks

### ISSUE THREAD

**Issue by wohlner** [livepeer/studio#369]
For example, are we going to use a message queue? Which one? ect.

@ya7ya will drive the creation of plan. @darkdarkdragon and @iameli are around for review. And of course, ask me (Jen) for product clarity.

**Comment by ericxtang** [comment]
I want to add some specific goals for this technical plan:
1. The plan should clearly list out the engineering tasks required to deliver the webhooks project scoped by @wohlner.  The engineering tasks should be 1 or 2 point issues.
2. The plan should answer important architectural questions. For ex: will we use a message queue? What kind? 
3. The plan should indicate performance and scale assumptions.  For ex: what will happen if thousands of concurrent streams happen at the same time?  
4. The plan should capture common corner cases.  For ex: what happens if the webhook endpoint provided by the user is down?  What if the ingest stream is broken in some way?  What happens if the cluster goes offline?  
5. The plan should include a clear timeline.
