### ISSUE TITLE
Scene Classification Webhook

### ISSUE THREAD

**Issue by iameli** [livepeer/studio#450]
Handle scene classification response from go-livepeer, passing it on to any users that have it registered.

The incoming go-livepeer webhook looks like this: https://github.com/livepeer/go-livepeer/issues/1917

Per discussion, our webhook object will look like:

```json5
{
    event: "scene.detected",
    url: "https://playdj.tv/api/livepeer-scene-detected",
    detection: {
        sceneClassification: [
            {name: "soccer"},
            {name: "adult"}
        ],
        
        // someday...
        objectDetection: [
            {name: "soccer ball"}
        ]
    }
}
```

**Comment by victorges** [comment]
What about using something like `stream.detection` for the event name? 
Or sth similar like `stream.sceneDetection`.

The prefix would keep consistency with the other events generated from streams like `stream.(active|idle)`.
And the `detection` would use the same name as the field that configures that specific event, which feels nice and tight to me.

Additionally, a follow up, what should we do in case there are multiple webhooks registered? Should we merge configurations when configuring the stream auth webhook and fan-out the events to the appropriate specific webhooks when receiving?

**Comment by victorges** [comment]
Just had another idea about this schema:

What if instead of having the detection configuration inside the webhook itself, we have it on the `stream` object themselves, but defaulting to some sane configuration in case the one on the stream doesn't exist but a detection webhook exists (global or specific)? 

I think that makes more sense to me than the webhook objects "understanding" the stream detection configurations, since the webhooks should rather be pretty simple instead with only information about type of event, URL to call and possibly scope of the event (currently only specific to a stream or global).

This would allow it to work for clients creating stream objects directly from Mist, since for now they will most likely just be using that default detection configuration anyway. In that default we will include every scene detection we currently have since they all run on the same model anyway.

In the (medium-term?) future, we will start having other scene classifications, but I believe they will likely remain on the same model so we can just include them in the "default" configuration, and by the time we actually have multiple models or classifications that clients want to configure in the low level, we will hopefully already have access to the mist plugin and be able to configure that payload as well, to make the config directly in the stream object.

To sum it up:
`webhook:`
```yaml
{
    event: "stream.detection",
    url: "https://playdj.tv/api/livepeer-scene-detected"
}
```

`stream:`
```yaml
{
    ... other stream stuff
    detection?: {
        sceneClassification: [
            {name: "soccer"},
            {name: "adult"}
        ],
        // someday...
        objectDetection: [
            {name: "soccer ball"}
        ]
    }
}
```
With the `detection` field being optional, and if not specified (and the webhook existing) will default to a configuration with all scenes for now, to be evaluated how to evolve later as more classifications are made available/configurable. In the future, we could even support a polling-based detection API, in case the stream is configured as such but the client doesn't want the webhook architecture.

**Comment by iameli** [comment]
@victorges Yep, that sounds reasonable. I think it makes total sense for it to live on the stream object itself - certainly makes it much more straightforward to handle the `authWebhookUrl` logic.
