### ISSUE TITLE
Change text to "Mute Audio"

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#663]
On the dashboard, on the stream detail page (homepage -> create stream), when creating a multistream destination there's a checkbox that reads "video only." This isn't clear that this check box removes the audio. 

Change this text to read "Mute Audio"

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/69574d6e-31c3-4101-8d35-dbff2bc04db7)

**Comment by victorges** [comment]
FTR, another possibility that I had thought was "Mute Audio" or "Silence Audio", WDYT? Probably just an english/wording issue so you probably know better, so just sharing the idea as food for thought.

Either way, mute/silence is actually more accurate to what really happens since Mist actually sends a silent audio instead of sending no audio track at all (that's relevant since some platforms like twitter don't accept streams without audio).

In that sense, those are also better than "video-only". I only called it that in the API so we can have the analogous "audio-only" option in the future, like for podcasts or something, but the wording in the frontend is independent. I think it should be whatever is clearest for the UI user at the current moment.

Lastly, might be necessary/interesting to update the Multistream docs as well. Maybe make a reference that this option in the Dashboard sets the respective video-only field in the API?

**Comment by pglowacky** [comment]
@victorges Great suggestion. I'll change it to "Mute Audio" as I think that's the absolute clearest and most accurate. Once changed, I'll update documentation

**Comment by victorges** [comment]
It's also consistent with mutestream! 🤪🤣

**Comment by FullStackTiger** [comment]
https://github.com/livepeer/livepeer-com/pull/691
