### ISSUE TITLE
www: "Stream Key" field should allow for Facebook-style query parameters

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#744]
> 
> Multistream works pretty well... Except in one specific case. When I create a LiveStream on Facebook manually and enter the RTMP url and the secret key, the multistream works without any problem. But if I use the Facebook Graph API to create this same Livestream, then the multistream fails without giving me any relevant information.
> 
> The only difference I see between the two attempts is the format of the secret key:
> 
> When it's a manual FB livestream, the key has the following format: FB-10222441839306395-0-AbyvkR4_l5uraYfb
> 
> When the FB livestream was created by the API, the key has the following format: 249915010556846?s_bl=1&s_psm=1&s_sw=0&s_vt=api-s&a=AbyLjYTtmztCPqeP
> 
> 
> Could the fact that there are query_params in the 2nd version create a problem on your side?

Can you make a suggestion on how to get around this? It's very important to the customer that he's able to multistream with Facebook.

**Comment by victorges** [comment]
@pglowacky Could you ask the customer to build the whole stream URL with that stream key, instead of inserting separate ingest URL and stream key?

i.e. if it were with our own streams, instead of filling the multistream target form with:
 - Ingest URL: `rtmp://rtmp.livepeer.com/live`
 - Stream key: `1234567?qs=v`

They would fill it like
 - Ingest URL: `rtmp://rtmp.livepeer.com/live/1234567?qs=v`
 - Stream key: `(empty)`

**Comment by victorges** [comment]
FTR, problem is probably this line: https://github.com/livepeer/livepeer-com/blob/eba0207340d77a1d04c2fc954b5aa6c269c42f67/packages/www/components/Dashboard/MultistreamTargetsTable/SaveTargetDialog.tsx#L66

We assume the stream key is only a path segment. Very weird that Facebook would try to inject querystrings in there assuming a service would only do a string append lol
But either way, building the full URL should work.
