### ISSUE TITLE
Improve Webhook Retry Logic and Notification 

### ISSUE THREAD

**Issue by pglowacky** [livepeer/studio#818]
_Open to tweaks and suggestions_

## Current State

From Victor:

>  - backoffs start at 5s and grow 20% on every error up to a maximum of 10 minutes
> - but with a plot twist, we only retry up to 20 times, so the max delay we actually have is 5*1.2^20=191s~3 minutes, total cumulative retry period of ~15.5min
 > * (all the above is easily tune-able for better retry behavior (just checked those numbers, seems like we can improve them a lot))
> - after those 15.5 minutes of retrying, we don't really send an email. we just log it for now, should be easy to send an email as well (not so easy to avoid spamming the user tho)

Breakdown of the existing (and proposed) exponential backoff schedule can be seen [here.](https://docs.google.com/spreadsheets/d/13yftN2gUV8t1I43SIlSlWdrUarqlw1ZvmPIXZKgusM4/edit#gid=0)

##  Improved State

**1) Notify customers when webhooks fail**
Right now, we don't tell customers when webhooks are failing. I propose that we notify customers at ~3min of retries via email. The email should include:

- Which webhook and URL is failing 
- When the endpoint will be automatically disabled

**2) Improve existing retry policy**
Our current retry policy only lasts for ~15.5 min, which is too short for customers to react to their webhooks failing. I propose that we alter the existing retry policy to  5s initial backoff, doubling backoffs exponentially until a maximum of 1 hr (3600s) and then retrying every hour for ~2 days. Seen here:

![image.png](https://images.zenhubusercontent.com/602ea479bcf4ef10a9aace61/570692bf-3740-45c7-99c6-958418d46668)

**Comment by victorges** [comment]
> I propose that we notify customers at ~3min of retries via email. The email should include:
> - Which webhook and URL is failing
> - When the endpoint will be automatically disabled

I think this sounds good, just some suggestions:
 - The email should also include the error/exception that happened, since we currently provide no other way for the user to investigate the errors that their webhooks are returning to our side. I think this should also be preferable than creating a UI or exposing an API to grab that information right now, unless we decide that we want to keep it in the long term.
 - We should probably give a little more time before sending an email to the user, since we don't want to spam them with too many emails on short periods of unavailability. Since we will already retry the webhook for >48h, WDYT of only actually emailing them when we reach the "max retry delay" (at the 11th attempt)? 
 That way, we can also give them a very exact threshold for them to fix their webhook before it is going to be automatically disabled, which we could set to be exactly 48h from the email (i.e. 48 additional retries after the email, total of 59 attempts).
 - I think we should also email the user again, after that last attempt that disables the webhook automatically. Just so they get a final confirmation that the automatic disabling actually happened. Not sure how to notify if the disabling was cancelled tho, which doesn't seem trivial.
 - To also avoid the spam, we should hold some kind of `lastEmailed` information in the webhook object in the database and email them at most once every hour, day, or sth like that. Just so we don't email the user for each and every event that starts erroring (e.g. for scene detection ones which are fired every 2 seconds, that would be a reeally uncomfortable experience for the user)
 - Regarding the automatic disabling, I think we should disable the webhook automatically for the **first event** that reaches the maximum retries. 
 i.e. even if some other events are working/being delivered fine, if a failing event reaches the final retry after 49.42h we should disable the webhook automatically.
 - Just a low-level code nit: we should also add some logic on the "delivery" (`_fireHook`) logic to re-fetch the current webhook state and stop calling it immediately in case it is disabled.
 - And this reminded me that we actually need to implement the feature for enabling/disabling webhooks, which does not exist yet (not in the API nor in the UI). Should be pretty straightforward, but necessary to keep in mind.

**Comment by victorges** [comment]
If we want just a quicker approach to this, we could also skip the (automatic) disabling of the webhook for now, and just email the user when we reach the final retry attempt and fail to deliver the payload to the webhook. On that case, we can include in the email not only the error that we received, but actually the whole payload that would be delivered to their webhook as well, so that they can re-deliver it themselves after they fix their service. 

On this version, we wouldn't even need/be able to have the `lastEmailed` anti-spam idea anyway, since the user might want to receive all the payloads that they received over email so they can retry later. So the solution is much simpler on our side:
 - Retry for some duration like 6-24h, which could be shorter since we won't be requiring users to react within that timeframe
 - After the last attempt, email the user with something like "your webhook failed to receive this payload", with the error and the exact payload that we sent (maybe even a little `curl` for them to try themselves directly)

I think the bigger downside of this solution is that we might accumulate some delayed events on our RabbitMQ if the users don't fix their webhooks. I think the periodic email should be annoying enough that they would eventually fix or delete the webhook anyway (if their email is real [1]). @pglowacky WDYT?

[1] Should we have some logic like not email them if the email is not verified? Could avoid spamming people that didn't even know that someone registered a Livepeer account with their email.

**Comment by gioelecerati** [comment]
I agree with this quicker approach and, as you said, there's need in the UI or on the API of a way to see if a webhook is enabled and a way to enable/disable it.

Since we are sending the email only when we reach the final retry attempt, there's a time frame of several hours where the webhook is failing and the user has not received any kind of notification yet, so:

- we could fire an event like `webhook.failed` or flag the webook with a `lastFailed` property so we can display on the UI an alert icon on a failing webhook? 
- It's not invasive as an email and gives the user some kind of notice, or in general a way to check if the configured webhook is working correctly without waiting for the notification, WDYT @victorges?

**Comment by victorges** [comment]
@gioelecerati I like the `lastFailed` idea very much! And it actually moves us 1 intermediate step towards actually exposing the result of all calls to webhooks, but with a safer interface that only guarantees showing 1 response (instead of creating an expectation on users for us to hold all the historical responses).

I think the `webhook.failed` could be kind of confusing/cyclic tho, cause users might normally just end up registering the same webhook for both the original event and the `webhook.failed` event, and so it's just another event that will fail in the end and create the risk of an endless webhook self-replication problem (we had that once 😆)

The "hardest" part of implementing the `lastFailed` (`lastFailure`?) field should be the frontend part. But I believe both that and the part of actually adding a field to webhook object, saving to db, etc, should be good exercises for you to get acquainted to the `livepeer-com` repo as a whole (frontend is also there under the `www` project).

WDYT of implementing that as a separate PR on top of the one for the email?

**Comment by gioelecerati** [comment]
@victorges Sounds good! I am actually thinking it could have a more specific property `webhookState` with both `lastFailure` and `lastSuccess`, comprehensive of `statusCode` and `responseError` (if present), so the frontend would just receive them from `/api/webhook` and the reason for the failure would be easily displayed as a title attribute on a warning icon for each failing webhook, how does that sound? There's not even need to keep updating the `lastFailure` state as soon as its timestamp is closer to now than the success one and the responseError is the same.
  
In a second moment this could also include the `isDisabled` state!

**Comment by victorges** [comment]
Hmm, I'm not sure if there would be much use for a `lastSuccess` field right now, since a success after the last failure does not mean that the webhook is working. It could just mean that some events are working and some are not. 

So in the UI, I think we might end up with only some "temporal" logic, like displaying a healthy/unhealthy badge (can even reuse the [`StatusBadge`](https://github.com/livepeer/livepeer-com/blob/9b12a1da82caf09b5d3ab6f65f706863e4cabaa0/packages/www/components/Dashboard/StatusBadge/index.tsx#L30) component from stream health ✨) depending on some failure happening in the past N hours (24h?). Although, we still might want to show something like `Idle` in case there are no failures but there are also no events that have been sent to the webhook over the same period. 

So how about:
```js
{
   ...otherStuff
  status: {
    lastTriggerTime: <timestamp>,
    lastFailure: { ... }
  }
}
```
with a status logic like:
  - if `lastTriggerTime < now() - 24h` => `Idle` with a tooltip "No events triggered in the past 24h"
  - else if `lastFailure > now() - 24h` => `Unhealthy` with a tooltip `Last error ${timeAgo.fromNow()}`
  - else `Healthy` with a tooltip `Last trigger ${timeAgo.fromNow()}`

And clicking on the Webhook would open that detailed view, which should show more information about the error.

Regarding the disabling field, I think it should just be a `disabled` boolean on the root to follow the pattern from some of our other resources. I also think that it is not a "status" thing anyway, since it's something that the user should be able to toggle themselves through the `PATCH` API.

Also, thinking further about the implementation details here I'm realizing that it might take some little time to implement anyway. Let's definitely keep this as a separate PR from the email fix that you're implementing, and as more priority tickets show up we can keep iterating on this one more in background.

**Comment by gioelecerati** [comment]
Ok cool, makes a lot of sense! I am going to keep it in a separate pull request.
