### ISSUE TITLE
Investigate all pertinent data happening around 503 errors

### ISSUE THREAD

**Issue by iameli** [livepeer/studio#943]

**Comment by figintern** [comment]
Load balancer (Traefik) 503's around time of incident (8am-11pm EST), VOD was reportedly flawless between 8-9pm and 503's were reported starting at 9:30AM EST.

https://eu-metrics-monitoring.livepeer.live/grafana/dashboard/snapshot/cK4H8Bx3i3fi7nys4d49hc3DydfjUfmb?orgId=1

**Comment by figintern** [comment]
From the dashboards it looks like 503's started as early as 9:00 PM EST, notably in LAX region, and subsided by about 10:10 PM EST

![image.png](https://images.zenhubusercontent.com/61f416c4a196dc3f3cc9dd96/04d428f8-50c9-4043-95dc-7d2a1f9db17b)

**Comment by figintern** [comment]
Some disk write failures in LAX at ~ 9:25PM EST, heavy traffic? 

https://eu-metrics-monitoring.livepeer.live/grafana/dashboard/snapshot/VM0X66rrIGCoGfkKotLh8zXbtcOFp1dI?orgId=1

**Comment by figintern** [comment]
Requests per minute of this stream showing the heavy traffic (~600 RPS) from 9:00 to 10:15

https://eu-metrics-monitoring.livepeer.live/grafana/dashboard/snapshot/ZRQyfbHrS6UC2Vo3cizE4e8rdtbbg9D9

![image.png](https://images.zenhubusercontent.com/61f416c4a196dc3f3cc9dd96/78cf2836-f640-4ea0-a5ac-bcfbad166c19)

**Comment by figintern** [comment]
load-testing session on Tuesday yielded that the 503's are likely caused by a mist configuration setting restricting the bandwidth each server is allowed to take on, causing them to fail health checks when the limit is breached under heavy request traffic. fix to increase the bandwidth from 1gbit to 30+ will be released for testing
